name: shellcheck

on: [push, pull_request]

# Based on documentation from https://github.com/azohra/shell-linter
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
